### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by neuecc** [Cysharp/MemoryPack#1]
- [x] CodeGenerator
  - [x] Standard Type
  - [x] Constructor
  - [x] Include Attribute
  - [x] Ignore Attribute
  - [x] Struct/record/struct record
  - [x] Callback Atrribute
  - [x] Derived
  - [x] Union
  - [x] Versioning
  - [x] Validate Recursive
  - [x] Generics
  - [x] Asynmmetric Type
  - [x] value kind optimization
  - [x] ref field, ref property, readonly, set only property
  - [x] generate external type
  - [x] Overwrite
  - [x] Optimize for Array/List,etc...
  - [x] unamanaged primitives optimize
  - [x] collect enum/generic/collection formatter register
- [x] StandardFormatter
  - [x] BitArray
  - [x] [,,]
  - [x] .NET 7 new primitives(Int128, UInt128)
  - [x] CollectionFormatter
    - [x] Overwrite
- [x] FormatterProvider
  - [x] Anonymous Type(throw not supported)
  - [x] Generic Factory
- [x] NonGenerics APIs
- [x] Streaming APIs
- [x] ReadMe
- [x] NuGet packaging
- [x] remove Unsafe.AsPointer
- [x] check generated code warning: https://github.com/Cysharp/MemoryPack/actions/runs/3123118669/jobs/5065525761
- [x] debugging aid
  - [x] summary
  - [x] csproj option to file-log https://github.com/dotnet/roslyn/blob/main/docs/features/source-generators.cookbook.md#consume-msbuild-properties-and-metadata
